### ISSUE TITLE
fix please....

### ISSUE THREAD

**Issue by LeePC** [FrankYang6921/mcdi#6]
python module : Pillow and mido

command : python main.py --midi "th08_10.mid" --save ".minecraft/saves/MCDI" --plugins "piano.PianoRoll(), piano.PianoRollFirework()" --kwargs "'single_tick_limit': 64"

python main.py --midi "th08_10.mid" --save ".minecraft/saves/MCDI" --plugins "piano.PianoRoll(), piano.PianoRollFirework()" --kwargs "'single_tick_limit': 64"
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    generator.loaded_messages()
TypeError: 'collections.deque' object is not callable

**Comment by FrankYang6921** [comment]
这个命令行版本已经停止维护了，以后用GUI就好，发布还要一段时间（
